scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1SZA.cif 1SZA.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/4ZPZ.cif 4ZPZ.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1J04.cif 1J04.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/5YY9.cif 5YY9.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/6J6M.cif 6J6M.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/7C7P.cif 7C7P.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/2THF.cif 2THF.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1B7V.cif 1B7V.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1HUY.cif 1HUY.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1FFM.cif 1FFM.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1AC5.cif 1AC5.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1I86.cif 1I86.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1B30.cif 1B30.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1A93.cif 1A93.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1M72.cif 1M72.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/6Y5D.cif 6Y5D.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/2XSK.cif 2XSK.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/1DIN.cif 1DIN.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/5VF5.cif 5VF5.cif
scp w3_pdb05@pdb-001:/nfs/public/services/onedep_gpfs/homes/mbage/test_pcm_model_gen/input/mmcifs/7AZ5.cif 7AZ5.cif
